{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-1.0.2.aar",
          "url": "admize-sdk-android-1.0.2.aar",
          "size": 1203937,
          "sha512": "038ded727797e9312584cb6d102a27bc67c9772d5cd05a204a4e3f60cdf1feb97d044b24a8016a170406f6b1c86850192ef67248cd887652562d4ec715e925e4",
          "sha256": "a4411bdd2abb989d7ce105c6d7bc47268390fafd73fea4b22f635b21f5ba6d6f",
          "sha1": "fb963b0e038949c1404f6d539798e76cfaec5d81",
          "md5": "018b9901ed7a15082950307220bb6345"
        }
      ]
    },
    {
      "name": "realDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-1.0.2.aar",
          "url": "admize-sdk-android-1.0.2.aar",
          "size": 1203937,
          "sha512": "038ded727797e9312584cb6d102a27bc67c9772d5cd05a204a4e3f60cdf1feb97d044b24a8016a170406f6b1c86850192ef67248cd887652562d4ec715e925e4",
          "sha256": "a4411bdd2abb989d7ce105c6d7bc47268390fafd73fea4b22f635b21f5ba6d6f",
          "sha1": "fb963b0e038949c1404f6d539798e76cfaec5d81",
          "md5": "018b9901ed7a15082950307220bb6345"
        }
      ]
    }
  ]
}
