{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.5.aar",
          "url": "admize-sdk-android-uat-1.0.5.aar",
          "size": 1204791,
          "sha512": "90ea1cf4f8fa0d8b607187290b1fd7059bef22114c166bec8bc4e8fc52c6645688c7b350e611eab1f9363e8a4e34ca2e5e95ec0f67e217c570e51989e0ec7a80",
          "sha256": "b21ce2c2d727f902742d85f1cfac0ed2ffa296504c906c09cfa8a863ca90fc08",
          "sha1": "146319a23de4d8763bce53c9b538e7231e4cd1f6",
          "md5": "c0c41b3d64a93a867e54daaf0d471b82"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.5.aar",
          "url": "admize-sdk-android-uat-1.0.5.aar",
          "size": 1204791,
          "sha512": "90ea1cf4f8fa0d8b607187290b1fd7059bef22114c166bec8bc4e8fc52c6645688c7b350e611eab1f9363e8a4e34ca2e5e95ec0f67e217c570e51989e0ec7a80",
          "sha256": "b21ce2c2d727f902742d85f1cfac0ed2ffa296504c906c09cfa8a863ca90fc08",
          "sha1": "146319a23de4d8763bce53c9b538e7231e4cd1f6",
          "md5": "c0c41b3d64a93a867e54daaf0d471b82"
        }
      ]
    }
  ]
}
