{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-1.0.13.aar",
          "url": "admize-sdk-android-1.0.13.aar",
          "size": 1145953,
          "sha512": "8075c579006df434599fa0c0901d2239e5f2001d346c45eea8179a0a230f7908a8a378be61db767ea2653632b013c1486eecf1275dd4434bdeeb684dc1bf5e0d",
          "sha256": "5e6c6bab3452c3866a7ed831846309d99e6f68da28bd27a92d6815a66c929647",
          "sha1": "3948c7fc889c83429d99e97f0acbc01f350cfb4d",
          "md5": "452fd723c17a46d27cb84dddb9e09d66"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-1.0.13.aar",
          "url": "admize-sdk-android-1.0.13.aar",
          "size": 1145953,
          "sha512": "8075c579006df434599fa0c0901d2239e5f2001d346c45eea8179a0a230f7908a8a378be61db767ea2653632b013c1486eecf1275dd4434bdeeb684dc1bf5e0d",
          "sha256": "5e6c6bab3452c3866a7ed831846309d99e6f68da28bd27a92d6815a66c929647",
          "sha1": "3948c7fc889c83429d99e97f0acbc01f350cfb4d",
          "md5": "452fd723c17a46d27cb84dddb9e09d66"
        }
      ]
    }
  ]
}
