{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-1.0.1.aar",
          "url": "admize-sdk-android-1.0.1.aar",
          "size": 1203936,
          "sha512": "a72fc2a4b9b6c174100c0e780a9e968f09d12276a8eef5207d5f5cc1c4f4e37531d0c97dde968457c36346a175bd3a0f5066b1d6f13d0f542e3617159c6ac336",
          "sha256": "c085116ee44a7c117a4942966e8f34b552cf3d6111623b2dd039c5c1439051fe",
          "sha1": "ea7051a609bc6b32c84cad46b2105f574e0ec878",
          "md5": "225de0243eb5c6013cdf342b0ad8afa3"
        }
      ]
    },
    {
      "name": "realDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-1.0.1.aar",
          "url": "admize-sdk-android-1.0.1.aar",
          "size": 1203936,
          "sha512": "a72fc2a4b9b6c174100c0e780a9e968f09d12276a8eef5207d5f5cc1c4f4e37531d0c97dde968457c36346a175bd3a0f5066b1d6f13d0f542e3617159c6ac336",
          "sha256": "c085116ee44a7c117a4942966e8f34b552cf3d6111623b2dd039c5c1439051fe",
          "sha1": "ea7051a609bc6b32c84cad46b2105f574e0ec878",
          "md5": "225de0243eb5c6013cdf342b0ad8afa3"
        }
      ]
    }
  ]
}
