{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android-uat",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "uatDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.15.aar",
          "url": "admize-sdk-android-uat-1.0.15.aar",
          "size": 1204819,
          "sha512": "23a92e34dcbb20b4cd9842afba9b17eda78205a9737048c3e4e59e2f4be8c81ac3bcf83e56e79037d965c507afae65be2ab05b05adb51a86ae8759da49ebc147",
          "sha256": "5bdc7e5d39f6aecc25d5b25e16851ed40c962f6f32a5ffbdbd4ce8175ce99107",
          "sha1": "8346a2ac88c91ffe9f463a31210d4072733f49cd",
          "md5": "457024261a84b6e941ddeba674c767ca"
        }
      ]
    },
    {
      "name": "uatDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-uat-1.0.15.aar",
          "url": "admize-sdk-android-uat-1.0.15.aar",
          "size": 1204819,
          "sha512": "23a92e34dcbb20b4cd9842afba9b17eda78205a9737048c3e4e59e2f4be8c81ac3bcf83e56e79037d965c507afae65be2ab05b05adb51a86ae8759da49ebc147",
          "sha256": "5bdc7e5d39f6aecc25d5b25e16851ed40c962f6f32a5ffbdbd4ce8175ce99107",
          "sha1": "8346a2ac88c91ffe9f463a31210d4072733f49cd",
          "md5": "457024261a84b6e941ddeba674c767ca"
        }
      ]
    }
  ]
}
