{
  "formatVersion": "1.1",
  "component": {
    "group": "io.admize.sdk.android",
    "module": "admize-sdk-android",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "realReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admize-sdk-android-1.0.16.aar",
          "url": "admize-sdk-android-1.0.16.aar",
          "size": 1145949,
          "sha512": "223abaf834d0871fa002a164f1c22ede8924958ffd1324d325aa409caa3cb8ebf12bb6186e11e3e5de6c62de7c9b1b5fe6bcdbe30a36cc65a74f7afefaf588b9",
          "sha256": "6f79ccab109b335c6441e24c966a5c2a7c3fe1f02a8143cecabd5cd771e6a50a",
          "sha1": "e175b9e9b9653c1efccb236bda9453094f4c4cb6",
          "md5": "218fbec99ed6cddf4a50ed0b4b93c82e"
        }
      ]
    },
    {
      "name": "realReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.2"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "admize-sdk-android-1.0.16.aar",
          "url": "admize-sdk-android-1.0.16.aar",
          "size": 1145949,
          "sha512": "223abaf834d0871fa002a164f1c22ede8924958ffd1324d325aa409caa3cb8ebf12bb6186e11e3e5de6c62de7c9b1b5fe6bcdbe30a36cc65a74f7afefaf588b9",
          "sha256": "6f79ccab109b335c6441e24c966a5c2a7c3fe1f02a8143cecabd5cd771e6a50a",
          "sha1": "e175b9e9b9653c1efccb236bda9453094f4c4cb6",
          "md5": "218fbec99ed6cddf4a50ed0b4b93c82e"
        }
      ]
    }
  ]
}
